### PR TITLE
1.8.x PLEASE!

### PR DESCRIPTION
**Pull request by seriousfreezing**
Do this mod to 1.8.x! PLEASE!

### CODE REVIEW

**Comment by Roadhog360** [comment]
This is not a pull request. You're just making a fake pull request with changes from my branch... This now permanently shows a dead PR in my GitHub Desktop app I cannot get rid of.

Backporting features is difficult and time-consuming, that is why there's very few mods for them. Please close this.

**Comment by DarianLStephens** [comment]
I was wondering what the heck this was, because there's no way a person who names and comments on a pull request like that would actually do the work.
They're probably someone very ne wto Github who has no clue what they're doing, and just found a part of the site that lets them leave a comment of some type (Though missing the issues tab).

**Comment by Roadhog360** [comment]
No, they didn't miss the issues tab, there is a post there too.

**Comment by Roadhog360** [comment]
@KryptonCaptain I know it's been a while, sorry to bother but can you please close this?

**Comment by KryptonCaptain** [comment]
Got it.

**Comment by Roadhog360** [comment]
Thanks, really appreciate it.

**Pull request closed without merging**
